version: '3'
services:
  rest-api:
    build: .
    command: npm start
    ports:
      - "9000:9000"
   
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=AlienDBex
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=pass
     
