services:
  rest-api:
    build: .
    command: node index.js
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=demo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
     
